Report build to quartz
Flexberry/Flexberry.AsyncOpenXmlReports.Sample pull request #19
Opened 2023-04-14 14:31 UTC by torres6093

2023-04-17 08:54 UTC, AntonIV8 requested changes

2023-04-17 08:54 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Controllers/CarListReportController.cs
> +                var templatePath = this.webHostEnvironment.ContentRootPath;
А это что ?

2023-04-17 08:54 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Controllers/CarListReportController.cs
> +                var userService = new CurrentHttpUserService(contextAccessor);
В конструктор метода принимаешь ICSSoft.Services.CurrentUserService.IUser  вместо contextAccessor.
Он в юнити зареган, должен разрешиться, не надо его вручную создавать

2023-04-17 08:54 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/AsyncOpenXmlReportsSample.sln
> +	ProjectSection(ProjectDependencies) = postProject
Это после чего добавилось ?

2023-04-17 08:54 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Controllers/CarListReportController.cs
> +                        Id = Guid.NewGuid().ToString(),
Мне кажется что это нужно в кварц перенести. id ведь только для маркировки джобов надо, пусть наверное там и будет

2023-04-17 08:54 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/Quartz/Flexberry.Quartz.Sample.Service/Flexberry.Quartz.Sample.Service.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
А это откуда появилось ?

2023-04-17 08:54 UTC, AntonIV8 commented on src/Docker/Dockerfile.Quartz
> +COPY /src/AsyncOpenXmlReportsSample /Quartz
А зачем ты в доке-файле изменил копирование проекта кварца на весь солюшен

2023-04-17 08:54 UTC, AntonIV8 commented on src/Docker/Dockerfile.Quartz
> + dotnet build Quartz/Flexberry.Quartz.Sample.sln -c Release;\
тут чет я не очень понял, у нас вроде нет Flexberry.Quartz.Sample.sln
Как эти две команды вообще выполняются ?

2023-04-17 10:28 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/appsettings.json
> +  "QuartzUrl": "http://localhost:5001/api/quartz/",
http://quartz:5001

2023-04-17 10:28 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/Controllers/CarListReportController.cs
> +                        TemplatePath = templatePath + @"\" + this.config["TemplatesPath"],
Не совсем понимаю зачем для кварца передавать какой-то путь шаблона. Достаточно передать имя шаблона, а квартц уже сам сформирует к нему путь, исходя из настроек, если оно вообще нужно передавать. Или у нас возможно использование одного метода квартца для формирования отчетов по разным шаблонам?

2023-04-17 10:28 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/Controllers/CarListReportController.cs
> +                return ex.Message;
Это плохо вывалить пользователям текст ошибки. Ошибку надо записать в лог. А пользователю сказать что-то типа "Извините".

2023-04-17 10:28 UTC, VChurekov commented on src/Docker/Dockerfile.Quartz
> +COPY /src/AsyncOpenXmlReportsSample /Quartz
Это скорее всего от того что в кварц добавились объекты из основного солюшена. Тут правильнее не менять эту строку, а добавить еще одну операцию COPY.

2023-04-17 10:36 UTC, AntonIV8 requested changes

2023-04-17 10:36 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/appsettings.json
> +  "QuartzUrl": "http://localhost:5001/api/quartz/",
Не-не, тут правильно. Значение QuartzUrl с именем докерного сервиса в docker-compose устанавливается

2023-04-17 10:53 UTC, merged

2023-04-18 05:35 UTC, VChurekov commented on src/Docker/Dockerfile.Quartz
> + dotnet build Quartz/Flexberry.Quartz.Sample.sln -c Release;\
Поправил.

2023-04-18 05:35 UTC, VChurekov commented on src/Docker/Dockerfile.Quartz
> +COPY /src/AsyncOpenXmlReportsSample /Quartz
Поправил.