Уведомление пользователя о формировании отчета.
Flexberry/Flexberry.AsyncOpenXmlReports.Sample pull request #37
Opened 2023-04-25 10:25 UTC by VChurekov

2023-04-25 11:05 UTC, AntonIV8 requested changes

2023-04-25 11:05 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Services/UsersReportsNotifier.cs
> +            var signalID = SignalRHub.GetUserID(username);
Тут получилась мешанина из staic методов хаба и hubContext. 
Во-первых static методы это последнее средство. Для начала попробуй в UsersReportsNotifier.cs все операции сигнала выполнять через this.hubContext.
Для этого пиши (hubContext as SignalRHub)

2023-04-25 11:05 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Services/UsersReportsNotifier.cs
> +            }
У хаба есть метод SendReportCompleteMessage для этого.

2023-04-25 11:05 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/SignalRHub.cs
> +        public static string GetUserID(string userName)
Если с (hubContext as SignalRHub) получится, то вместо этого метода будет метод public bool CheckUserForConnection(string userName)

2023-04-25 11:05 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/SignalRHub.cs
> +                await Clients.Client(id).SendAsync("NotifyUser", $"{username}! {message}").ConfigureAwait(false);
А что делает ConfigureAwait(false) ?

2023-04-25 11:05 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/SignalRHub.cs
> +        /// Метод вызывается из клиента (ember-фронтенда) SignalR. Выполняет вызов метода на стороне клиента.
Метод очень похож на предыдущий, может хоть в комментарии написать, что это именно оповещалка о завершении запроса, а первый метод просто оповещался хоть о чем. 
Но вообще, я бы все что касается SendNotifyUserMessage (и на фронте) убрал. Этот метод оформился в более конкретный SendReportCompleteMessage

2023-04-25 11:12 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/Services/UsersReportsNotifier.cs
> +            var signalID = SignalRHub.GetUserID(username);
Я так пробовал. hubContext as SignalRHub = null.

2023-04-25 11:16 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/SignalRHub.cs
> +                await Clients.Client(id).SendAsync("NotifyUser", $"{username}! {message}").ConfigureAwait(false);
На это сонар ругался... Но вот выдержки из статей хабра.
https://habr.com/ru/articles/482354/

ConfigureAwait(continueOnCapturedContext: false) используется для предотвращения принудительного вызова коллбэка в исходном контексте или планировщике. 

Это дает нам несколько преимуществ:
Улучшение производительности.
Предотвращение дедлоков.

2023-04-25 14:09 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/SignalRHub.cs
> +        /// Метод вызывается из клиента (ember-фронтенда) SignalR. Выполняет вызов метода на стороне клиента.
Я просто не стал убирать старый функционал по тестированию уведомления пользователя.

2023-04-25 14:10 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/SignalRHub.cs
> +        public static string GetUserID(string userName)
Перенесено в интефейс ISignarRClientsService.

2023-04-25 14:10 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/Services/UsersReportsNotifier.cs
> +            }
Теперь нет.

2023-04-26 05:29 UTC, AntonIV8 requested changes

2023-04-26 05:29 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Services/SignarRClientsService.cs
> +                return users.First(p => p.Key == userId).Value;
а тут не просто users[userId] ?

2023-04-26 05:29 UTC, AntonIV8 commented on src/AsyncOpenXmlReportsSample/ODataBackend/Startup.cs
> +            container.RegisterInstance<ISignarRClientsService>(new SignarRClientsService());
тут вроде надо указать еще Lifetime Singleton

2023-04-26 07:32 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/Startup.cs
> +            container.RegisterInstance<ISignarRClientsService>(new SignarRClientsService());
Указал.

2023-04-26 07:32 UTC, VChurekov commented on src/AsyncOpenXmlReportsSample/ODataBackend/Services/SignarRClientsService.cs
> +                return users.First(p => p.Key == userId).Value;
Поправил.

2023-04-26 11:43 UTC, AntonIV8 approved these changes

2023-04-26 11:43 UTC, merged