Data and user service.
Flexberry/Flexberry.AsyncOpenXmlReports.Sample pull request #7
Opened 2023-04-11 07:51 UTC by VChurekov

2023-04-11 08:08 UTC, AntonIV8 requested changes

2023-04-11 08:08 UTC, AntonIV8 commented on src/Quartz/Flexberry.Quartz.Sample.Service/AdapterStartup.cs
> +            services.AddScoped<IUserWithRoles, AdapterUserService>();
Наверное надо технологические сервисы через Unity сделать. Везде так

2023-04-11 08:08 UTC, AntonIV8 commented on src/Quartz/Flexberry.Quartz.Sample.Service/Controllers/QuartzController.cs
> +                job.JobDataMap.Add("SQLDataService", ds as SQLDataService);
Тут мб Postgres, идентично чтобы было

2023-04-11 08:27 UTC, VChurekov commented on src/Quartz/Flexberry.Quartz.Sample.Service/Controllers/QuartzController.cs
> +                job.JobDataMap.Add("SQLDataService", ds as SQLDataService);
SQLDataService более общий класс. Это позволит инициализировать например MSSQLDataService, вместо PostgresDataService, и в задании ничего менять не надо. Привел к SQLDataService вместо IDataService, потому что потребовалось вытащить свойство CustomizationString.

2023-04-12 11:20 UTC, VChurekov commented on src/Quartz/Flexberry.Quartz.Sample.Service/AdapterStartup.cs
> +            services.AddScoped<IUserWithRoles, AdapterUserService>();
Переделал.

2023-04-12 11:21 UTC, VChurekov commented on src/Quartz/Flexberry.Quartz.Sample.Service/Controllers/QuartzController.cs
> +                job.JobDataMap.Add("SQLDataService", ds as SQLDataService);
В итоге перенесли в другое место.

2023-04-12 12:04 UTC, bratchikov requested changes

2023-04-12 12:04 UTC, bratchikov commented on src/Quartz/Flexberry.Quartz.Sample.Service/Adapter.cs
> +        public static readonly IUnityContainer Container = UnityFactory.GetContainer();
Спроси у Тани как сделать так, чтобы не использовать UnityFactory - мы от неё избавляемся.

2023-04-12 12:04 UTC, bratchikov commented on src/Quartz/Flexberry.Quartz.Sample.Service/AdapterService.cs
> +﻿using Microsoft.AspNetCore;
Если я правильно помню наши настройки стилей, то using-и мы внутри неймспейса размещаем. Подключены анализаторы и Flexberry.ruleset?

2023-04-12 12:04 UTC, bratchikov commented on src/Quartz/Flexberry.Quartz.Sample.Service/Jobs/TestJob.cs
>      public class TestJob : IJob
Это какой-то тест? Если да, то почему он не в тестовом проекте? Лучше какие-то осмысленные задачи делать.

2023-04-13 04:33 UTC, AntonIV8 approved these changes

2023-04-13 04:49 UTC, bratchikov approved these changes

2023-04-13 05:37 UTC, merged